tasks:
  - name: Backend
    init: |
      pip install --upgrade pip
      pip install -r requirements.txt
    command: |
      uvicorn backend:app --reload --host 0.0.0.0 --port 8000
    openMode: split-right

  - name: Frontend
    init: |
      cd frontend
      npm install
    command: |
      cd frontend
      npm run dev
    openMode: split-left

github:
  prebuilds:
    branches:
      main: true
      feature/*: true

ports:
  - port: 8000
    onOpen: open-preview
  - port: 5173
    onOpen: open-preview

env:
  ANTHROPIC_API_KEY: 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
  SEARCH_PROVIDER: SEARXNG
  SEARXNG_URL: http://192.168.1.10:4000
  SEARXNG_RESULTS: 5
  TAVILY_API_KEY: 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
  CLAUDE_MODEL: claude-3-5-sonnet-latest
  MAX_ITERATIONS: 5
